### ISSUE TITLE
lodash missing

### ISSUE THREAD

**Issue by colobas** [calculist/calculist-desktop#1]
Running ``` $ /usr/bin/electron /path/to/calculist ``` throws the following error:

```
App threw an error during load
Error: Cannot find module 'lodash'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/usr/lib/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/colobas/work/calculist-desktop/main.js:2:11)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'lodash'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/usr/lib/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/colobas/work/calculist-desktop/main.js:2:11)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

Solved by running ``` $ npm install lodash --save ``` inside the calculist-desktop folder

**Comment by danallison** [comment]
Hi @colobas . Dependencies are declared in `package.json`. If you run `npm install` while in the `calculist-desktop` directory, that should should install all necessary node modules, including lodash. Then, you can run `npm start` to start the app in dev mode.

**Comment by colobas** [comment]
Hi @danallison ! Sorry, I'm a node noob. I do love your app, keep up the great work! :+1:

**Comment by danallison** [comment]
No problem. I really should add a README file to make it easier to get up and running. I will get to that soon.
